/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FeedCell.java
 *
 * Created on Feb 15, 2010, 9:02:52 PM
 */

package dk.profundo.drfeeds;

import dk.profundo.drpodcasts.PodCastItem;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author ermh
 */
public class FeedCell extends javax.swing.JPanel implements ListCellRenderer {

    /** Creates new form FeedCell */
    public FeedCell() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        body = new javax.swing.JLabel();

        title.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        title.setText("Alle Tiders Historie");

        body.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        body.setText("<html>Alle Tiders Histore er levende historieformidling, der tager rundt i landet for at fortælle om de mennesker og begivenheder, der har præget vores fælles fortid og sætter spor i vores samtid.");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(title, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .add(body, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(title)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(body, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel body;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        PodCastItem item = (PodCastItem) value;
        body.setText(item.description);
        title.setText(item.title);
        
        setBackground(isSelected ? Color.LIGHT_GRAY : Color.WHITE);
        return this;
    }

}
