/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FeedPanel.java
 *
 * Created on Feb 14, 2010, 12:06:04 PM
 */

package dk.profundo.drfeeds;

/**
 *
 * @author ermh
 */
public class FeedPanel extends javax.swing.JPanel {
    FeedTableModel model = new FeedTableModel();

    /** Creates new form FeedPanel */
    public FeedPanel() {
        initComponents();
        scrollableList1.setModel(model);
        scrollableList1.setCellRenderer(new FeedCell());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entryTable = new javax.swing.JList();
        loadFeeds = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        scrollableList1 = new dk.profundo.drfeeds.ScrollableList();

        entryTable.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        entryTable.setFixedCellWidth(200);

        loadFeeds.setText("Load Feeds");
        loadFeeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFeedsActionPerformed(evt);
            }
        });

        scrollableList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(scrollableList1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(loadFeeds)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(loadFeeds))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadFeedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFeedsActionPerformed
        model.load(this);
    }//GEN-LAST:event_loadFeedsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList entryTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadFeeds;
    private dk.profundo.drfeeds.ScrollableList scrollableList1;
    // End of variables declaration//GEN-END:variables

}
